# @format

name: main

on:
    pull_request:
        types: [assigned, opened, synchronize, reopened]
    push:
        branches:
            - main
            - develop
            - 'releases/**'
            - 'features/**'
jobs:
    version:
        name: Calculate Version
        runs-on: ubuntu-latest
        outputs:
          semVer: ${{ steps.gitversion.outputs.semVer }} # To use an output in another job, you have to map it to a job output.
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: '5.x'
            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0.9.7
            - name: Display SemVer
              run: |
                  echo "SemVer: $GITVERSION_SEMVER"
    tests:
        name: Continuous Integration
        runs-on: ubuntu-latest
        needs: version
        env:
            APP_ENV: testing
            SEMVER: ${{ needs.version.outputs.semVer }}
        steps:
            - uses: actions/checkout@v2
            - name: Set Version
              run: echo $SEMVER > VERSION
            - uses: c-hive/gha-npm-cache@v1
            - name: Setup Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '12'
                  check-latest: true
            - name: Install npm dependencies
              run: npm install
            - name: Run JS tests
              run: npm run test
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4 # Use your PHP version
                  extensions: mbstring, bcmath # Setup any required extensions for tests
            - name: Install composer dependencies
              uses: ramsey/composer-install@v1
            - name: Run PHP Tests
              run: |
                  php artisan env
                  composer test
